import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/AppLayout";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";
import { Jost } from 'next/font/google'

// import ThemeProvider from "@/provider/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ['latin'],
   weight: ['300', '400', '500', '600', '700', '800', '900'],
})



const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:5000/api/store");
  const store = await res.json();

  
  return (
    <html>
      <body>
        <ClientWrapper>

          <AppLayout backendTheme={store.activeTheme}>{children}</AppLayout>
        </ClientWrapper>
      </body>
    </html>
  );
}
