export const DataModernFashionCategoryBigDetailedSection = [
    {
        id: 1,
        title: "Clothing",
        description:
            "Lorem Ipsum is simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing.",
        categoryPic: "/ThemeModernFashion/category1.png",
        smallCategoryPic: "/ThemeModernFashion/smallCategory1.png",
        flexReverse: false,
        buttonProps: {
            text: "Shop Now",
            href: "/products",
            bgColor: "bg-transparent",
            textColor: "text-black",
            hoverBgColor: "bg-black",
            hoverTextColor: "text-white",
            border: "border-2 border-black",
            rounded: "rounded-none",
            padding: "px-7",
            height: "h-11",
        },
    },
    {
        id: 2,
        title: "SHOES",
        description:
            "Lorem Ipsum is simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing.",
       categoryPic: "/ThemeModernFashion/category2.png",
        smallCategoryPic: "/ThemeModernFashion/smallCategory2.png",
        flexReverse: true,
        buttonProps: {
            text: "Shop Now",
            href: "/products",
            bgColor: "bg-transparent",
            textColor: "text-black",
            hoverBgColor: "bg-black",
            hoverTextColor: "text-white",
            border: "border-2 border-black",
            rounded: "rounded-none",
            padding: "px-7",
            height: "h-11",
        },
    },
    {
        id: 2,
        title: "Accessories",
        description:
            "Lorem Ipsum is simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing simply dummy text of the printing.",
       categoryPic: "/ThemeModernFashion/category3.png",
        smallCategoryPic: "/ThemeModernFashion/smallCategory3.png",
        flexReverse: false,
        buttonProps: {
            text: "Shop Now",
            href: "/products",
            bgColor: "bg-transparent",
            textColor: "text-black",
            hoverBgColor: "bg-black",
            hoverTextColor: "text-white",
            border: "border-2 border-black",
            rounded: "rounded-none",
            padding: "px-7",
            height: "h-11",
        },
    },
];