
const DataModernFashionLatestProductCarousel = [
    {
        id: 1,
        image: "/ThemeModernFashion/update1.png",
        title: "Everything You Didn't Know About Yourself",
        date: "2024/11/27",
        comments: 0,
        excerpt: "One may not need charts and graphs at this point to know that, in the past couple of years...",
    },
    {
        id: 2,
        image: "/ThemeModernFashion/update2.png",
        title: "Unlock the Full Potential of Collection",
        date: "2024/11/27",
        comments: 0,
        excerpt: "One may not need charts and graphs at this point to know that, in the past couple of years...",
    },
    {
        id: 3,
        image: "/ThemeModernFashion/update3.png",
        title: "The Art of Choosing the Perfect Timepiece",
        date: "2024/11/20",
        comments: 3,
        excerpt: "A watch is more than a timekeeping device — it's an extension of your personality and style...",
    },
    {
        id: 4,
        image: "/ThemeModernFashion/update4.png",
        title: "How Minimalism Changed the Sneaker Game",
        date: "2024/11/15",
        comments: 5,
        excerpt: "Less is more — a philosophy that has quietly reshaped the footwear industry over the last decade...",
    },
    {
        id: 5,
        image: "/ThemeModernFashion/update5.png",
        title: "Running Gear That Actually Makes a Difference",
        date: "2024/11/10",
        comments: 2,
        excerpt: "Investing in the right gear can transform your runs from a chore into something you look forward to...",
    },
    {
        id: 6,
        image: "/ThemeModernFashion/update6.png",
        title: "Fragrance Layering: A Beginner's Guide",
        date: "2024/11/05",
        comments: 7,
        excerpt: "The secret to a signature scent isn't finding one perfect perfume — it's learning how to layer them...",
    },
    {
        id: 7,
        image: "/ThemeModernFashion/update7.png",
        title: "Why Leather Goods Never Go Out of Style",
        date: "2024/10/28",
        comments: 1,
        excerpt: "From belts to wallets, leather accessories carry a timeless quality that synthetic materials simply can't replicate...",
    },
    {
        id: 8,
        image: "/ThemeModernFashion/update8.png",
        title: "Packing Smart: The Carry-On Only Challenge",
        date: "2024/10/20",
        comments: 4,
        excerpt: "Traveling light isn't just about saving baggage fees — it's a mindset shift that changes how you experience travel...",
    },
    {
        id: 9,
        image: "/ThemeModernFashion/update9.png",
        title: "Camera Accessories Worth Every Penny",
        date: "2024/10/15",
        comments: 6,
        excerpt: "The right accessories don't just improve your photos — they change the way you see the world through a lens...",
    },
    {
        id: 10,
        image: "/ThemeModernFashion/update10.png",
        title: "Headphones That Redefine What Audio Means",
        date: "2024/10/08",
        comments: 9,
        excerpt: "In a world flooded with audio options, a select few pairs of headphones stand apart for the experience they deliver...",
    },
];

export default DataModernFashionLatestProductCarousel;