import React, { Suspense } from "react";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/AppLayout";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";
import { Jost } from 'next/font/google'

// import ThemeProvider from "@/provider/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ['latin'],
   weight: ['300', '400', '500', '600', '700', '800', '900'],
})



const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  // backend removed – choose a static default theme or allow preview via URL
  // you can change this value to any key from `src/lib/theme.js` or
  // rely on the provider's fallback (currently `time`).

  // http://localhost:3000/?previewTheme=beauty
  const defaultTheme = "time";

  return (
    <html>
      <body>
        <Suspense fallback={null}>
          <ClientWrapper>
            <AppLayout backendTheme={defaultTheme}>{children}</AppLayout>
          </ClientWrapper>
        </Suspense>
      </body>
    </html>
  );
}
