export const DataDynamicGrid = [
    {
        id: 1,
        image: "/ThemeClothing/grid1.png",
        category: "SHOP",
        title: "MENS",
        categoryColor: "text-white",
        titleColor: "text-white",
        grid: "row-span-2",
       
        // textAlign: "center",
        buttonProps: {
            text: "SHOP NOW",
            textColor: "text-white",
            bgColor: "bg-transparent",
            padding: "px-10",
            border: "border border-1 border-white",
            onClick: () => router.push("/shop"),
        },
    },
    {
        id: 2,
        image: "/ThemeClothing/grid2.png",
        category: "CLOTHING",
        title: "SPRING SUMMER\nCOLLECTION",
        subtitle: "From $189/product",
        categoryColor: "text-gray-600",
        titleColor: "text-black",
        subtitleColor: "text-black",
        itemStart: true,
        textAlign:"left",
         contentAlign: "left",
        buttonProps: {
            text: "SHOP NOW",
            onlyBottomBorder: true,
            textColor: "text-black",
            onClick: () => router.push("/shop"),
        },
    },
    {
        id: 4,
        image: "/ThemeClothing/grid4.png",
        category: "SHOP",
        title: "WOMEN",
        grid: "row-span-2",
        categoryColor: "text-white",
        titleColor: "text-white",
        buttonProps: {
            text: "SHOP NOW",
            textColor: "text-white",
            bgColor: "bg-transparent",
            padding: "px-10",
            border: "border border-1 border-white",
            onClick: () => router.push("/shop"),
        },
    },
    {
        id: 3,
        image: "/ThemeClothing/grid3.png",
        category: "CLOTHING",
        title: "S-S2018 Shoes\nCollection",
        subtitle: "From $189/product",
        categoryColor: "text-gray-600",
        titleColor: "text-black",
        subtitleColor: "text-black",
        itemStart: true,
         textAlign:"left",
         contentAlign: "left",
        buttonProps: {
            text: "SHOP NOW",
            onlyBottomBorder: true,
            textColor: "text-black",
            onClick: () => router.push("/shop"),
        },
    },

]