export const DataProductGlassesTheme = [
  {
    id: 1,
    name: "Classic Black Frame Glasses",
    category: "latest",
    image: "/ThemeGlasses/glasses1.png",
    price: 4200,
    comparePrice: 5200,
    rating: 4.7,
    bestseller: true,
    description:
      "Premium lightweight acetate frame.\nScratch-resistant clear lenses.\nComfortable nose pads for daily wear.\nSuitable for both casual and formal looks.\nTimeless and versatile design.",
  },
  {
    id: 2,
    name: "Modern Transparent Frame Glasses",
    category: "featured",
    image: "/ThemeGlasses/glasses2.png",
    price: 3600,
    comparePrice: 4500,
    rating: 4.6,
    bestseller: true,
    description:
      "Crystal-clear stylish frame.\nUltra-lightweight construction.\nAnti-glare coated lenses.\nPerfect for office and everyday use.\nMinimal and trendy appearance.",
  },
  {
    id: 3,
    name: "Premium Metal Rim Glasses",
    category: "latest",
    image: "/ThemeGlasses/glasses3.png",
    price: 5200,
    comparePrice: 6500,
    rating: 4.8,
    bestseller: true,
    description:
      "Durable stainless steel frame.\nSlim and elegant rim design.\nAdjustable nose pads.\nComfortable all-day wear.\nSophisticated professional style.",
  },
  {
    id: 4,
    name: "Elegant Gold Frame Glasses",
    category: "featured",
    image: "/ThemeGlasses/glasses4.png",
    price: 4800,
    comparePrice: 6200,
    rating: 4.5,
    bestseller: false,
    description:
      "Luxury gold-tone metal frame.\nLightweight and durable build.\nHigh-clarity lenses.\nPerfect for formal and special occasions.\nRefined and premium look.",
  },
  {
    id: 5,
    name: "Casual Round Frame Glasses",
    category: "latest",
    image: "/ThemeGlasses/glasses10.png",
    price: 1600,
    comparePrice: 2200,
    rating: 4.4,
    bestseller: false,
    description:
      "Trendy round frame style.\nComfort-fit temples.\nClear anti-scratch lenses.\nIdeal for daily casual wear.\nLightweight and durable material.",
  },
  {
    id: 6,
    name: "Athletic Sport Glasses",
    category: "featured",
    image: "/ThemeGlasses/glasses6.png",
    price: 6900,
    comparePrice: 8500,
    rating: 4.9,
    bestseller: true,
    description:
      "Impact-resistant frame.\nFlexible and secure fit.\nUV protection lenses.\nDesigned for active lifestyles.\nComfortable grip for long wear.",
  },
  {
    id: 7,
    name: "Oversized Fashion Glasses",
    category: "latest",
    image: "/ThemeGlasses/glasses7.png",
    price: 2300,
    comparePrice: 3000,
    rating: 4.3,
    bestseller: false,
    description:
      "Bold oversized frame design.\nLightweight acetate material.\nStylish and modern appearance.\nComfortable temple support.\nPerfect for fashion-forward looks.",
  },
  {
    id: 8,
    name: "Classic Brown Frame Glasses",
    category: "featured",
    image: "/ThemeGlasses/glasses8.png",
    price: 1900,
    comparePrice: 2600,
    rating: 4.5,
    bestseller: false,
    description:
      "Warm brown finish frame.\nDurable flexible material.\nClear high-precision lenses.\nSuitable for smart-casual styling.\nComfortable everyday wear.",
  },
  {
    id: 9,
    name: "Luxury Designer Glasses",
    category: "latest",
    image: "/ThemeGlasses/glasses9.png",
    price: 8800,
    comparePrice: 10500,
    rating: 4.8,
    bestseller: true,
    description:
      "Premium handcrafted frame.\nHigh-definition anti-glare lenses.\nElegant modern shape.\nPerfect for professional settings.\nSuperior comfort and durability.",
  },
  {
    id: 10,
    name: "Slim Minimalist Glasses",
    category: "featured",
    image: "/ThemeGlasses/glasses10.png",
    price: 3600,
    comparePrice: 4500,
    rating: 4.6,
    bestseller: true,
    description:
      "Ultra-slim lightweight frame.\nMinimal modern design.\nComfortable nose support.\nClear vision lenses.\nIdeal for everyday and office wear.",
  },
];