export const DataModernFashionProductCardWithHoverButton = [
  {
    id: 1,
    image: "/ThemeModernFashion/grid1.png",
    alt: "Prada Leather Bag",
    category: "Bags",
    buttonProps: {
      text: "Shop Bags",
      href: "/products",
      bgColor: "bg-transparent",
      textColor: "text-white",
      border: "border-2 border-white",
      rounded: "rounded-none",
      padding: "px-8",
      height: "h-11",
    },
  },
  {
    id: 2,
    image: "/ThemeModernFashion/grid2.png",
    alt: "Brown Brogue Oxford Shoes",
    category: "Shoes",
    buttonProps: {
      text: "Shop Shoes",
      href: "/products",
      bgColor: "bg-transparent",
      textColor: "text-white",
    //   hoverBgColor: "bg-white",
    //   hoverTextColor: "text-black",
      border: "border-2 border-white",
      rounded: "rounded-none",
      padding: "px-8",
      height: "h-11",
    },
  },
  {
    id: 3,
    image: "/ThemeModernFashion/grid3.png",
    alt: "Luxury Chronograph Watch",
    category: "Watches",
    buttonProps: {
      text: "Shop Watches",
      href: "/products",
      bgColor: "bg-transparent",
      textColor: "text-white",
      border: "border-2 border-white",
      rounded: "rounded-none",
      padding: "px-8",
      height: "h-11",
    },
  },
];