export const DataProductWatchTheme = [
  {
    id: 1,
    name: "Classic Chrono Watch",
    category: "latest",
    image: "/ThemePictures/watch10.jpeg",
    price: 120,
    comparePrice: 150,
    rating: 4.5,
    bestseller: true,
    color: "Black",
    tag: "Classic",
    brand: "Classic Chrono",
    description: "A classic chronograph watch with a timeless design that never goes out of style. Perfect for both casual and formal wear, making it versatile for any occasion. High-precision movement ensures accurate timekeeping throughout your day. Durable strap designed for all-day comfort without irritation. Scratch-resistant glass for long-lasting clarity and protection. A perfect blend of style and functionality that complements any wardrobe."
  },
  {
    id: 2,
    name: "Minimal Silver Watch",
    category: "featured",
    image: "/ThemePictures/watch6.jpeg",
    price: 80,
    comparePrice: 100,
    rating: 3.8,
    bestseller: false,
     color: "Gray",
    tag: "Casual",
    brand: "Minimal",
    description: "A minimal silver watch with a clean modern look that defines contemporary style. Designed for everyday elegance and simplicity without compromising on quality. Lightweight build for comfortable daily use that you'll barely notice on your wrist. Reliable quartz movement for precise timing that keeps you punctual. Pairs well with any outfit or occasion, from business meetings to weekend outings. Ideal choice for minimal watch lovers who appreciate understated sophistication."
  },
  {
    id: 3,
    name: "Luxury Black Dial Watch",
    category: "topRated",
    image: "/ThemePictures/watch7.jpeg",
    price: 200,
    comparePrice: 250,
    rating: 3.9,
    bestseller: true,
      color: "Black",
    tag: "Luxury",
    brand: "Luxury",
    description: "A luxury watch featuring a bold black dial that commands attention wherever you go. Enhances your style with a premium appearance that speaks volumes about your taste. Crafted with high-quality stainless steel that ensures longevity and durability. Smooth finishing for a sophisticated look that never fails to impress. Suitable for business meetings and formal events where first impressions matter. Built to last with durable materials that withstand the test of time."
  },
  {
    id: 5,
    name: "Premium Gold Watch",
    category: "latest",
    image: "/ThemePictures/watch8.jpeg",
    price: 900,
    comparePrice: 350,
    rating: 4.7,
    bestseller: false,
    color: "Gold",
    tag: "Luxury",
    brand: "Premium",
    description: "A premium gold watch with an elegant finish that radiates luxury and class. Designed for those who love the finer things in life and aren't afraid to show it. High-quality build with precise movement that demonstrates superior craftsmanship. Comfortable strap for extended wear during long days and special occasions. Perfect for weddings, galas, and upscale events where you want to make a statement. Adds a bold statement to your wrist that showcases your success and refined taste."
  },
  {
    id: 6,
    name: "Rose Gold Watch",
    category: "latest",
    image: "/ThemePictures/watch9.jpeg",
    price: 600,
    comparePrice: 350,
    rating: 2.6,
    bestseller: false,
    color: "Rose Gold",
    tag: "Modern",
    brand: "Premium",
    description: "A stylish rose gold watch with a modern touch that brings warmth to your accessories. Perfect for casual and semi-formal outfits, bridging the gap between relaxed and refined. Smooth dial with easy-to-read markers that ensure you're never late for important appointments. Lightweight and comfortable for daily wear without causing any strain or discomfort. Reliable performance with durable materials that maintain their luster over time. A trendy addition to your watch collection that reflects current fashion sensibilities."
  },
  {
    id: 7,
    name: "Smart Casual Watch",
    category: "latest",
    image: "/ThemePictures/watch10.jpeg",
    price: 400,
    comparePrice: 350,
    rating: 4.3,
    bestseller: false,
  color: "Blue",
    tag: "Casual",
    brand: "Smart",
    description: "A smart casual watch designed for everyday use that adapts to your lifestyle seamlessly. Balanced design suitable for work and outings, making it incredibly versatile for modern life. High-quality strap ensures comfort throughout your busy day without any irritation. Accurate timekeeping with quartz movement that you can depend on for precision. Modern dial enhances overall appearance with contemporary aesthetics that stay current. Ideal for daily wear and gifting to someone special who appreciates practical elegance."
  },
  {
    id: 8,
    name: "Luxury Metal Watch",
    category: "latest",
    image: "/ThemePictures/watch11.jpeg",
    price: 900,
    comparePrice: 350,
    rating: 4.1,
    bestseller: false,
    color: "Gray",
    tag: "Luxury",
    brand: "Luxury",
    description: "A luxury metal watch with a bold and strong look that exudes confidence and power. Perfect for men who prefer premium accessories that make a statement without saying a word. Durable metal strap for long-term use that maintains its shine and structural integrity. Elegant dial design with fine detailing that showcases meticulous craftsmanship and attention. Suitable for formal events and party wear where you need to stand out from the crowd. A statement watch for confident personalities who lead rather than follow trends."
  },
  {
    id: 9,
    name: "Casual Everyday Watch",
    category: "latest",
    image: "/ThemePictures/watch12.jpeg",
    price: 400,
    comparePrice: 350,
    rating: 3.7,
    bestseller: false,
     color: "White",
    tag: "Casual",
    brand: "Smart",
    description: "A casual watch built for everyday comfort that becomes your reliable daily companion. Simple yet stylish design that proves less is often more in the world of accessories. Reliable quartz movement ensures accuracy so you're always on time for life's important moments. Comfortable strap for long wear during extended days at work or weekend adventures. Perfect for daily routines and travel, fitting seamlessly into any lifestyle or situation. A practical and stylish choice that delivers value without compromising on appearance or quality."
  },
  {
    id: 10,
    name: "Modern Leather Watch",
    category: "latest",
    image: "/ThemePictures/watch13.jpeg",
    price: 700,
    comparePrice: 350,
    rating: 3.4,
    bestseller: false,
   color: "Black",
    tag: "Modern",
    brand: "Premium",
    description: "A modern watch with a premium leather strap that combines traditional materials with contemporary design. Designed for elegance and durability, ensuring it remains a wardrobe staple for years to come. Clean dial with minimal detailing that embodies the sophistication of modern minimalism. Comfortable fit for long hours at the office or during extended business dinners and meetings. Ideal for office and formal occasions where professional appearance matters most. Enhances your overall style effortlessly, adding a touch of refinement to any ensemble you choose."
  },
  {
    id: 11,
    name: "Elegant Classic Watch",
    category: "latest",
    image: "/ThemePictures/watch14.jpeg",
    price: 800,
    comparePrice: 350,
    rating: 4.2,
    bestseller: false,
    color: "Gold",
    tag: "Classic",
    brand: "Classic Chrono",
    description: "An elegant classic watch with a timeless appeal that transcends fleeting fashion trends. Perfect for both casual and formal wear, making it an investment piece worth owning. High-quality materials ensure durability that can be passed down through generations as an heirloom. Smooth finish with premium detailing that reflects expert craftsmanship and attention to detail. Reliable performance for everyday use without the need for constant adjustments or maintenance. A great gift choice for watch lovers who appreciate enduring quality and traditional excellence."
  },
  {
    id: 12,
    name: "Simple Dial Watch",
    category: "latest",
    image: "/ThemePictures/watch15.jpeg",
    price: 400,
    comparePrice: 350,
    rating: 3.7,
    bestseller: false,
   color: "White",
    tag: "Casual",
    brand: "Minimal",
    description: "A simple dial watch with a clean design that emphasizes clarity and ease of use. Ideal for those who prefer minimal styling without unnecessary complications or decorative elements. Easy-to-read dial with precise markers that make checking the time effortless at a glance. Lightweight and comfortable construction that you can wear all day without fatigue or discomfort. Perfect for daily and casual wear, adapting to various settings from gym to grocery store. Reliable and stylish at the same time, proving that simplicity can be incredibly sophisticated."
  },
  {
    id: 13,
    name: "Stylish Analog Watch",
    category: "latest",
    image: "/ThemePictures/watch16.jpeg",
    price: 700,
    comparePrice: 350,
    rating: 3.4,
    bestseller: false,
    color: "Blue",
    tag: "Modern",
    brand: "Smart",
    description: "A stylish analog watch with modern aesthetics that bridges classic watchmaking with contemporary design. Designed to complement any outfit from casual jeans to tailored suits with equal ease. Strong build with quality materials that ensure this watch can handle your active lifestyle. Comfortable strap for daily use that doesn't dig into your wrist or cause skin irritation. Accurate movement for reliable performance that keeps you punctual for all your appointments. A smart choice for everyday fashion that demonstrates your appreciation for well-designed accessories."
  },
];