import beauty from "@/themes/beauty";
import bookStore from "@/themes/bookStore";
import ceramic from "@/themes/ceramic";
import classicCosmetics from "@/themes/classicCosmetics";
import classicElectro from "@/themes/classicElectro";
import classicFurniture from "@/themes/classicFurniture";
import clothing from "@/themes/clothing";
import cosmetics from "@/themes/cosmetics";
import electroHub from "@/themes/electroHub";
import electroMart from "@/themes/electroMart";
import fashion from "@/themes/fashion";
import furniture from "@/themes/furniture";
import glasses from "@/themes/glasses";
import jewellery from "@/themes/jewellery";
import kids from "@/themes/kids";
import modernFashion from "@/themes/modernFashion";
import modestWear from "@/themes/modestWear";
import perfume from "@/themes/perfume";
import time from "@/themes/time";
import toys from "@/themes/toys";

export const THEMES = { time , furniture, classicFurniture, beauty, perfume, cosmetics, clothing, fashion, classicElectro, electroHub, electroMart, jewellery, classicCosmetics, modestWear, modernFashion, glasses, ceramic, toys, bookStore, kids};
