export const DataProductFashionTheme = [
  {
    id: 1,
    name: "Classic White Sneakers",
    category: "latest",
    image: "/ThemeFashion/fashion1.png",
    price: 4200,
    comparePrice: 5200,
    rating: 4.7,
    bestseller: true,
    description: "Minimalist sneaker design.\nComfortable cushioned sole.\nDurable everyday footwear.\nPerfect for casual outfits.\nStylish and versatile look."
  },
  {
    id: 2,
    name: "Leather Crossbody Bag",
    category: "featured",
    image: "/ThemeFashion/fashion2.png",
    price: 3600,
    comparePrice: 4500,
    rating: 4.6,
    bestseller: true,
    description: "Premium leather finish.\nCompact yet spacious design.\nIdeal for daily essentials.\nAdjustable shoulder strap.\nModern fashion accessory."
  },
  {
    id: 3,
    name: "Denim Jacket",
    category: "latest",
    image: "/ThemeFashion/fashion3.png",
    price: 5200,
    comparePrice: 6500,
    rating: 4.8,
    bestseller: true,
    description: "Classic denim style.\nHigh-quality fabric.\nPerfect for layering outfits.\nComfortable regular fit.\nTimeless fashion piece."
  },
  {
    id: 4,
    name: "Stylish Wrist Watch",
    category: "featured",
    image: "/ThemeFashion/fashion4.png",
    price: 4800,
    comparePrice: 6200,
    rating: 4.5,
    bestseller: false,
    description: "Elegant dial design.\nDurable metal strap.\nWater-resistant build.\nPerfect for formal wear.\nPremium fashion watch."
  },
  {
    id: 5,
    name: "Casual Graphic T-Shirt",
    category: "latest",
    image: "/ThemeFashion/fashion5.png",
    price: 1600,
    comparePrice: 2200,
    rating: 4.4,
    bestseller: false,
    description: "Soft cotton fabric.\nTrendy graphic print.\nBreathable and lightweight.\nIdeal for everyday wear.\nEasy to style with jeans."
  },
  {
    id: 6,
    name: "Running Sports Shoes",
    category: "featured",
    image: "/ThemeFashion/fashion6.png",
    price: 6900,
    comparePrice: 8500,
    rating: 4.9,
    bestseller: true,
    description: "High-performance running shoes.\nShock-absorbing sole.\nBreathable mesh design.\nExcellent grip and comfort.\nPerfect for workouts."
  },
  {
    id: 7,
    name: "Elegant Sunglasses",
    category: "latest",
    image: "/ThemeFashion/fashion7.png",
    price: 2300,
    comparePrice: 3000,
    rating: 4.3,
    bestseller: false,
    description: "UV-protected lenses.\nModern frame design.\nLightweight and durable.\nPerfect for sunny days.\nEnhances fashion appeal."
  },
  {
    id: 8,
    name: "Formal Leather Belt",
    category: "featured",
    image: "/ThemeFashion/fashion8.png",
    price: 1900,
    comparePrice: 2600,
    rating: 4.5,
    bestseller: false,
    description: "Genuine leather material.\nStrong metal buckle.\nPerfect for formal outfits.\nDurable daily accessory.\nClassic fashion essential."
  },
  {
    id: 9,
    name: "Hooded Winter Jacket",
    category: "latest",
    image: "/ThemeFashion/fashion9.png",
    price: 8800,
    comparePrice: 10500,
    rating: 4.8,
    bestseller: true,
    description: "Warm insulated design.\nWind-resistant fabric.\nStylish hooded look.\nIdeal for cold weather.\nComfort-focused stitching."
  },
  {
    id: 10,
    name: "Comfort Fit Jogger Pants",
    category: "featured",
    image: "/ThemeFashion/fashion10.png",
    price: 2900,
    comparePrice: 3600,
    rating: 4.4,
    bestseller: false,
    description: "Relaxed modern fit.\nSoft stretchable fabric.\nPerfect for casual wear.\nBreathable material.\nAll-day comfort guaranteed."
  },
    {
    id: 11,
    name: "Canvas Casual Backpack",
    category: "latest",
    image: "/ThemeFashion/fashion11.png",
    price: 3400,
    comparePrice: 4200,
    rating: 4.6,
    bestseller: true,
    description: "Spacious everyday backpack.\nDurable canvas material.\nMultiple storage compartments.\nComfortable shoulder straps.\nPerfect for daily use."
  },
  {
    id: 12,
    name: "Slip-On Loafers",
    category: "featured",
    image: "/ThemeFashion/fashion12.png",
    price: 4600,
    comparePrice: 5800,
    rating: 4.7,
    bestseller: true,
    description: "Elegant slip-on design.\nSoft inner cushioning.\nIdeal for formal and casual wear.\nLightweight and comfortable.\nStylish modern finish."
  },
  {
    id: 13,
    name: "Classic Analog Watch",
    category: "latest",
    image: "/ThemeFashion/fashion13.png",
    price: 5200,
    comparePrice: 6500,
    rating: 4.5,
    bestseller: false,
    description: "Timeless analog design.\nPremium metal casing.\nDurable strap quality.\nPerfect for everyday fashion.\nMinimal yet elegant look."
  },
  {
    id: 14,
    name: "Oversized Hoodie",
    category: "featured",
    image: "/ThemeFashion/fashion14.png",
    price: 3800,
    comparePrice: 4600,
    rating: 4.6,
    bestseller: true,
    description: "Trendy oversized fit.\nSoft fleece interior.\nIdeal for winter wear.\nStylish street fashion.\nMaximum comfort and warmth."
  },
  {
    id: 15,
    name: "Women’s Handbag",
    category: "latest",
    image: "/ThemeFashion/fashion15.png",
    price: 6100,
    comparePrice: 7500,
    rating: 4.8,
    bestseller: true,
    description: "Elegant structured handbag.\nPremium leather texture.\nSpacious inner compartments.\nPerfect for formal outings.\nLuxury fashion accessory."
  },
  {
    id: 16,
    name: "Formal Oxford Shoes",
    category: "featured",
    image: "/ThemeFashion/fashion16.png",
    price: 7200,
    comparePrice: 8800,
    rating: 4.9,
    bestseller: true,
    description: "Classic Oxford shoe design.\nHigh-quality leather upper.\nComfortable cushioned sole.\nPerfect for office wear.\nSharp and professional look."
  },
  {
    id: 17,
    name: "Printed Silk Scarf",
    category: "latest",
    image: "/ThemeFashion/fashion17.png",
    price: 1900,
    comparePrice: 2500,
    rating: 4.4,
    bestseller: false,
    description: "Soft silk fabric.\nElegant printed patterns.\nLightweight and breathable.\nPerfect fashion layering piece.\nEnhances any outfit."
  },
  {
    id: 18,
    name: "Slim Fit Chinos",
    category: "featured",
    image: "/ThemeFashion/fashion18.png",
    price: 4100,
    comparePrice: 5200,
    rating: 4.6,
    bestseller: false,
    description: "Modern slim-fit design.\nComfortable stretch fabric.\nPerfect for smart casual looks.\nBreathable material.\nEveryday fashion essential."
  },

];
