export const DataToysProductBigPictureWithCarousel = [
  {
    id: 1,
    name: "Blabla Kid Fruit Rattle Pear",
    price: "$79.00",
    // badge: "SOLD OUT",
    href: "/shop",
    carouselImage: "/ThemeToys/smallProduct2.png",
    bigImage: "/ThemeToys/bigProduct1.png",
    alt: "Blabla Kid Fruit Rattle Pear knitted toy",
    bigAlt: "Baby playing with knitted fruit toys",
  },
  {
    id: 2,
    name: "Blabla Kid Fruit Rattle Banana",
    price: "$65.00",
    // badge: null,
    href: "/shop",
     carouselImage: "/ThemeToys/smallProduct2.png",
    bigImage: "/ThemeToys/bigProduct2.png",
    alt: "Blabla Kid Fruit Rattle Banana knitted toy",
    bigAlt: "Baby holding knitted banana toy",
  },
  {
    id: 3,
    name: "Blabla Kid Fruit Rattle Orange",
    price: "$65.00",
    // badge: "NEW",
    href: "/shop",
     carouselImage: "/ThemeToys/smallProduct3.png",
    bigImage: "/ThemeToys/bigProduct3.png",
    alt: "Blabla Kid Fruit Rattle Orange knitted toy",
    bigAlt: "Baby playing with knitted orange toy",
  },
];