export const DataProductCeramicTheme = [
  {
    id: 1,
    name: "Handcrafted Ceramic Vase",
    category: "latest",
    image: "/ThemeCeramic/ceramic1.png",
    price: 4200,
    comparePrice: 5200,
    rating: 4.7,
    bestseller: true,
    description: "Hand-thrown premium ceramic.\nSmooth glazed finish.\nElegant minimalist design.\nPerfect for home decor or gifting.\nDurable and timeless craftsmanship."
  },
  {
    id: 2,
    name: "Modern Ceramic Dinner Plate Set",
    category: "featured",
    image: "/ThemeCeramic/ceramic2.png",
    price: 3600,
    comparePrice: 4500,
    rating: 4.6,
    bestseller: true,
    description: "High-quality stoneware ceramic.\nScratch-resistant glazed surface.\nPerfect for everyday dining.\nDishwasher safe and durable.\nElegant modern aesthetic."
  },
  {
    id: 3,
    name: "Artisan Ceramic Coffee Mug",
    category: "latest",
    image: "/ThemeCeramic/ceramic3.png",
    price: 5200,
    comparePrice: 6500,
    rating: 4.8,
    bestseller: true,
    description: "Handcrafted pottery design.\nComfortable grip handle.\nHeat-retaining thick walls.\nPerfect for coffee and tea.\nUnique rustic finish."
  },
  {
    id: 4,
    name: "Luxury Ceramic Serving Bowl",
    category: "featured",
    image: "/ThemeCeramic/ceramic4.png",
    price: 4800,
    comparePrice: 6200,
    rating: 4.5,
    bestseller: false,
    description: "Premium glazed ceramic.\nDeep spacious design.\nIdeal for salads and serving dishes.\nChip-resistant surface.\nElegant dining essential."
  },
  {
    id: 5,
    name: "Decorative Ceramic Planter",
    category: "latest",
    image: "/ThemeCeramic/ceramic5.png",
    price: 1600,
    comparePrice: 2200,
    rating: 4.4,
    bestseller: false,
    description: "Durable fired clay material.\nModern textured finish.\nPerfect for indoor plants.\nDrainage-friendly base.\nStylish home accent piece."
  },
  {
    id: 6,
    name: "Ceramic Tea Cup & Saucer Set",
    category: "featured",
    image: "/ThemeCeramic/ceramic6.png",
    price: 6900,
    comparePrice: 8500,
    rating: 4.9,
    bestseller: true,
    description: "Elegant handcrafted design.\nSmooth glossy glaze.\nHeat-resistant ceramic.\nPerfect for tea gatherings.\nClassic and refined look."
  },
  {
    id: 7,
    name: "Hand-Painted Ceramic Wall Plate",
    category: "latest",
    image: "/ThemeCeramic/ceramic7.png",
    price: 2300,
    comparePrice: 3000,
    rating: 4.3,
    bestseller: false,
    description: "Intricate hand-painted artwork.\nPremium quality ceramic.\nReady-to-hang design.\nAdds artistic charm to walls.\nLong-lasting vibrant colors."
  },
  {
    id: 8,
    name: "Minimalist Ceramic Soap Dispenser",
    category: "featured",
    image: "/ThemeCeramic/ceramic8.png",
    price: 1900,
    comparePrice: 2600,
    rating: 4.5,
    bestseller: false,
    description: "Smooth matte ceramic finish.\nRust-resistant pump.\nPerfect for kitchen or bathroom.\nRefillable and eco-friendly.\nModern minimalist style."
  },
  {
    id: 9,
    name: "Large Ceramic Fruit Bowl",
    category: "latest",
    image: "/ThemeCeramic/ceramic9.png",
    price: 8800,
    comparePrice: 10500,
    rating: 4.8,
    bestseller: true,
    description: "Spacious handcrafted design.\nPremium glazed surface.\nIdeal for fruits or centerpieces.\nDurable and chip-resistant.\nElegant statement piece."
  },
  {
    id: 10,
    name: "Textured Ceramic Vase Set",
    category: "featured",
    image: "/ThemeCeramic/ceramic10.png",
    price: 3600,
    comparePrice: 4500,
    rating: 4.6,
    bestseller: true,
    description: "Set of two matching vases.\nUnique textured surface.\nPerfect for dried or fresh flowers.\nNeutral modern tones.\nEnhances living space decor."
  },
  {
    id: 11,
    name: "Rustic Ceramic Storage Jar",
    category: "latest",
    image: "/ThemeCeramic/ceramic11.png",
    price: 2300,
    comparePrice: 3000,
    rating: 4.3,
    bestseller: false,
    description: "Airtight wooden lid.\nHandcrafted rustic finish.\nIdeal for kitchen storage.\nDurable thick ceramic body.\nStylish and functional design."
  },
  {
    id: 12,
    name: "Elegant Ceramic Candle Holder",
    category: "latest",
    image: "/ThemeCeramic/ceramic12.png",
    price: 4800,
    comparePrice: 6200,
    rating: 4.5,
    bestseller: false,
    description: "Smooth glazed ceramic.\nStable sturdy base.\nPerfect for table decor.\nMinimal and elegant shape.\nIdeal for modern interiors."
  },
  {
    id: 13,
    name: "Handcrafted Ceramic Dinner Bowl",
    category: "latest",
    image: "/ThemeCeramic/ceramic13.png",
    price: 4800,
    comparePrice: 6200,
    rating: 4.5,
    bestseller: false,
    description: "Deep versatile bowl design.\nPremium quality clay.\nMicrowave and dishwasher safe.\nPerfect for soups and pasta.\nDurable everyday essential."
  },
];